### ISSUE TITLE
baidu_url_submit无法找到count

### ISSUE THREAD

**Issue by wolfdan666** [leafjame/hexo-theme-next5-leaf#1]
![image](https://user-images.githubusercontent.com/37760924/66103368-19d3e000-e5e8-11e9-81db-eacca2435a3c.png)

**Comment by leafjame** [comment]
这需要依赖 [hexo-baidu-url-submit](https://github.com/huiwang/hexo-baidu-url-submit) 插件，主动推送Hexo博客新链接至百度搜索引擎，配置可参考文末提供的 站点配置文件：[baidu_url_submit](https://github.com/leafjame/hexo-theme-next5-leaf#%E6%9C%80%E5%90%8E)

**Comment by wolfdan666** [comment]
是的,就是`npm i`之后,就出现了这个问题,然后我把这个插件关了,就可以了,但是肯定就无法推送给百毒了,不知道这个count是哪个count

**Comment by leafjame** [comment]
安装这款插件后，注册百度搜索平台账号后，在https://ziyuan.baidu.com/site/index 里，有个链接提交：
![image](https://user-images.githubusercontent.com/29299658/66105168-49391b80-e5ed-11e9-8e8c-d2f59e0ae8fe.png)
在下方的 自动提交--》推送接口--》接口调用地址 有 token 值，把这些信息填入**站点配置文件** baidu_url_submit 位置即可，这个 count 就是提交最新的链接数，正确操作后是没有问题的。
