### ISSUE TITLE
天气那里怎么自动识别ip更换地点

### ISSUE THREAD

**Issue by wolfdan666** [leafjame/hexo-theme-next5-leaf#2]
大哥,您好,天气那里怎么自动识别ip更换地点,我看见你的站点可以自动识别ip更换城市,但是我在网上找了很多方法, 好像还是不会,所以又来issue了

**Comment by leafjame** [comment]
使用的那个 iframe 插件自带这个功能了，插件地址：http://www.tianqi.com/plugin/  ， 下方的 **天气代码定制 --> 默认城市** 那里就有配置（不选则时系统自动判断访问者IP所在地并显示该地区天气）。
我目前使用的是 [2345天气插件](https://tianqi.2345.com/plugin/) 了，主要是基于https的考虑，不过不影响。
天气插件在博客中的配置地址：`/themes/主题名称/layout/_macro/carousel.swig`。

**Comment by wolfdan666** [comment]
好的，谢谢，我明天试试



---原始邮件---
发件人: "北宸"<notifications@github.com&gt;
发送时间: 2019年10月10日(星期四) 晚上11:27
收件人: "leafjame/hexo-theme-next5-leaf"<hexo-theme-next5-leaf@noreply.github.com&gt;;
抄送: "wolfdan666"<862445752@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [leafjame/hexo-theme-next5-leaf] 天气那里怎么自动识别ip更换地点 (#2)



使用的那个iframe插件自带这个功能了，插件地址：http://www.tianqi.com/plugin/  ， 下方的 天气代码定制 --&gt; 默认城市 那里就有配置。
 博客配置地址：/themes/主题/layout/_macro/carousel.swig。
 我目前使用的是 2345天气插件 了，主要是基于https的考虑，不过不影响。

**Comment by wolfdan666** [comment]
谢谢啦,成功了
