### ISSUE TITLE
为什么这个文件库无法push

### ISSUE THREAD

**Issue by wolfdan666** [leafjame/hexo-theme-next5-leaf#3]
![image](https://user-images.githubusercontent.com/37760924/67145688-e4044c00-f2b5-11e9-932a-fea8876c0143.png)
我发现我今天用另一台设备准备操作的时候在自己的云端私有库里面没有这个文件，然后测试了好多次，发现leaf文件无法push，不知道是什么奇怪问题，我试了下，next下和
leaf添加文件，只有next能push到云端，而leaf出现一个这样的状况

云端： coding的私有库   （我用这个来备份）

**Comment by leafjame** [comment]
看下是不是给加到了 .gitignore 中了

**Comment by wolfdan666** [comment]
没有的，我检查了好几次
```
.DS_Store
Thumbs.db
db.json
*.log
node_modules/
public/
.deploy*/
```

**Comment by leafjame** [comment]
是没有执行  git add 这个命令吧？

**Comment by wolfdan666** [comment]
![image](https://user-images.githubusercontent.com/37760924/67146368-28dfb100-f2bd-11e9-9fb6-d45e8d9aa0da.png)


哈哈哈，其实我觉得这个问题很神奇，可能我要更深入得了解更多的git的知识才能懂为什么会这样

**Comment by leafjame** [comment]
切换到 themes 目录，执行 `git add .` 试试， add 后边有个点哦

**Comment by wolfdan666** [comment]
https://blog.csdn.net/zixiao217/article/details/86693854

谢谢大哥，我直接去leaf的根目录尝试了，然后终于有报错了，然后顺着报错找到了解决办法，谢谢
